import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    appName: 'EcoGuardian',
    map: 'Map',
    report: 'Report',
    issues: 'Issues',
    research: 'Research',
    database: 'Database',
    settings: 'Settings',
    theme: '🌓 Theme',
    light: 'Light',
    dark: 'Dark',
    language: '🌐 Language',
    success: '✅ Issue reported successfully!',
    error: '❌ Failed to report issue',
    deleteConfirm: 'Are you sure you want to delete this issue?',
    deleteSuccess: '✅ Issue deleted successfully',
    deleteError: '❌ Failed to delete issue',
    resolveSuccess: '✅ Issue marked as resolved!',
    resolveError: '❌ Failed to resolve issue',
    editSuccess: '✅ Issue updated successfully!',
    editError: '❌ Failed to update issue',
    loading: 'Loading...',
    backendError: '⚠️ Cannot connect to backend server. Please make sure the server is running on port 5001',
    noLocation: 'Please select a location on the map first',
    fillFields: 'Please fill all required fields',
    districtSelected: '📍 {{district}} district selected',
    // Report Form translations
    reportTitle: 'Report Environmental Issue',
    title: 'Title',
    titlePlaceholder: 'Enter issue title',
    description: 'Description',
    descriptionPlaceholder: 'Describe the environmental issue...',
    district: 'District',
    selectDistrict: 'Select district',
    location: 'Location',
    selectedLocation: 'Selected Location',
    latitude: 'Latitude',
    longitude: 'Longitude',
    images: 'Images',
    uploadImages: 'Upload Images',
    dragImages: 'Click or drag images to upload',
    mapImages: 'Map/Satellite Images',
    uploadMapImages: 'Upload Map or Satellite Images',
    dragMapImages: 'Click or drag map/satellite images to upload',
    pdfs: 'PDF Documents',
    uploadPDFs: 'Upload PDF Documents',
    dragPDFs: 'Click or drag PDF documents to upload',
    submitReport: 'Submit Report',
    cancel: 'Cancel',
    backToMap: 'Back to Map',
    // Issues List translations
    environmentalIssues: 'Environmental Issues',
    searchIssues: 'Search issues...',
    filterByStatus: 'Filter by status',
    all: 'All',
    open: 'Open',
    resolved: 'Resolved',
    inProgress: 'In Progress',
    noIssuesFound: 'No issues found',
    noIssuesReported: 'No environmental issues reported yet',
    beFirst: 'Be the first to report an issue',
    reportNewIssue: 'Report New Issue',
    delete: 'Delete',
    edit: 'Edit',
    resolve: 'Resolve',
    connectResearch: 'Connect Research',
    viewDetails: 'View Details',
    status: 'Status',
    reportedOn: 'Reported on',
    reportedBy: 'Reported by',
    actions: 'Actions',
    resolutionNotes: 'Resolution Notes',
    enterResolutionNotes: 'Enter resolution notes...',
    resolveIssue: 'Resolve Issue',
    confirmResolve: 'Confirm Resolve',
    editIssue: 'Edit Issue',
    updateIssue: 'Update Issue',
    // Research Panel translations
    researchHub: 'Research Hub',
    environmentalResearch: 'Environmental Research',
    searchResearch: 'Search research...',
    filterByType: 'Filter by type',
    allTypes: 'All Types',
    scientificPaper: 'Scientific Paper',
    caseStudy: 'Case Study',
    report: 'Report',
    news: 'News',
    addResearch: 'Add Research',
    title: 'Title',
    type: 'Type',
    description: 'Description',
    link: 'Link',
    author: 'Author',
    publishedDate: 'Published Date',
    tags: 'Tags',
    connectToIssue: 'Connect to Issue',
    noResearchFound: 'No research found',
    addNewResearch: 'Add New Research',
    // Database Viewer translations
    databaseViewer: 'Database Viewer',
    collectionStats: 'Collection Statistics',
    issuesCount: 'Issues',
    researchCount: 'Research',
    usersCount: 'Users',
    refresh: 'Refresh',
    exportData: 'Export Data',
    collection: 'Collection',
    documents: 'Documents',
    viewDocument: 'View Document',
    close: 'Close',
    rawData: 'Raw Data',
    // Toast notifications
    toastSuccess: 'Success',
    toastError: 'Error',
    toastInfo: 'Info',
    toastWarning: 'Warning',
  },
  si: {
    appName: 'පරිසර ආරක්ෂක',
    map: 'සිතියම',
    report: 'වාර්තා කරන්න',
    issues: 'ගැටළු',
    research: 'පර්යේෂණ',
    database: 'දත්ත සංචිතය',
    settings: 'සැකසීම්',
    theme: '🌓 තේමාව',
    light: 'ආලෝකය',
    dark: 'අඳුරු',
    language: '🌐 භාෂාව',
    success: '✅ ගැටළුව සාර්ථකව වාර්තා කරන ලදී!',
    error: '❌ ගැටළුව වාර්තා කිරීම අසාර්ථකයි',
    deleteConfirm: 'ඔබට මෙම ගැටළුව මකා දැමීමට අවශ්‍ය බව විශ්වාසද?',
    deleteSuccess: '✅ ගැටළුව සාර්ථකව මකා දමන ලදී',
    deleteError: '❌ ගැටළුව මකා දැමීම අසාර්ථකයි',
    resolveSuccess: '✅ ගැටළුව විසඳුනු ලෙස සලකුණු කරන ලදී!',
    resolveError: '❌ ගැටළුව විසඳීමට අසමත්',
    editSuccess: '✅ ගැටළුව සාර්ථකව යාවත්කාලීන කරන ලදී!',
    editError: '❌ ගැටළුව යාවත්කාලීන කිරීම අසාර්ථකයි',
    loading: 'පූරණය වෙමින්...',
    backendError: '⚠️ බැක්‍එන්ඩ් සේවාදායකයට සම්බන්ධ විය නොහැක. කරුණාකර සේවාදායකය 5001 තොටේ ක්‍රියාත්මක වන බවට වග බලා ගන්න',
    noLocation: 'කරුණාකර පළමුව සිතියමේ ස්ථානයක් තෝරන්න',
    fillFields: 'කරුණාකර අවශ්‍ය සියලු ක්ෂේත්‍ර පුරවන්න',
    districtSelected: '📍 {{district}} දිස්ත්‍රික්කය තෝරාගත්තා',
    // Report Form translations
    reportTitle: 'පාරිසරික ගැටළුව වාර්තා කරන්න',
    title: 'මාතෘකාව',
    titlePlaceholder: 'ගැටළු මාතෘකාව ඇතුළත් කරන්න',
    description: 'විස්තරය',
    descriptionPlaceholder: 'පාරිසරික ගැටළුව විස්තර කරන්න...',
    district: 'දිස්ත්‍රික්කය',
    selectDistrict: 'දිස්ත්‍රික්කය තෝරන්න',
    location: 'ස්ථානය',
    selectedLocation: 'තෝරාගත් ස්ථානය',
    latitude: 'අක්ෂාංශය',
    longitude: 'දේශාංශය',
    images: 'පින්තූර',
    uploadImages: 'පින්තූර උඩුගත කරන්න',
    dragImages: 'උඩුගත කිරීමට පින්තූර ක්ලික් කරන්න හෝ ඇද දමන්න',
    mapImages: 'සිතියම්/චන්ද්‍රිකා පින්තූර',
    uploadMapImages: 'සිතියම් හෝ චන්ද්‍රිකා පින්තූර උඩුගත කරන්න',
    dragMapImages: 'උඩුගත කිරීමට සිතියම්/චන්ද්‍රිකා පින්තූර ක්ලික් කරන්න හෝ ඇද දමන්න',
    pdfs: 'PDF ලේඛන',
    uploadPDFs: 'PDF ලේඛන උඩුගත කරන්න',
    dragPDFs: 'උඩුගත කිරීමට PDF ලේඛන ක්ලික් කරන්න හෝ ඇද දමන්න',
    submitReport: 'වාර්තාව ඉදිරිපත් කරන්න',
    cancel: 'අවලංගු කරන්න',
    backToMap: 'සිතියමට ආපසු',
    // Issues List translations
    environmentalIssues: 'පාරිසරික ගැටළු',
    searchIssues: 'ගැටළු සොයන්න...',
    filterByStatus: 'තත්වය අනුව පෙරහන් කරන්න',
    all: 'සියල්ල',
    open: 'විවෘත',
    resolved: 'විසඳා ඇත',
    inProgress: 'ප්‍රගතියේ',
    noIssuesFound: 'ගැටළු හමු නොවීය',
    noIssuesReported: 'තවම පාරිසරික ගැටළු වාර්තා කර නැත',
    beFirst: 'පළමුව ගැටළුව වාර්තා කරන්න',
    reportNewIssue: 'නව ගැටළුවක් වාර්තා කරන්න',
    delete: 'මකන්න',
    edit: 'සංස්කරණය කරන්න',
    resolve: 'විසඳන්න',
    connectResearch: 'පර්යේෂණ සම්බන්ධ කරන්න',
    viewDetails: 'විස්තර බලන්න',
    status: 'තත්වය',
    reportedOn: 'වාර්තා කළ දිනය',
    reportedBy: 'වාර්තා කළේ',
    actions: 'ක්‍රියා',
    resolutionNotes: 'විසඳුම් සටහන්',
    enterResolutionNotes: 'විසඳුම් සටහන් ඇතුළත් කරන්න...',
    resolveIssue: 'ගැටළුව විසඳන්න',
    confirmResolve: 'විසඳීම තහවුරු කරන්න',
    editIssue: 'ගැටළුව සංස්කරණය කරන්න',
    updateIssue: 'ගැටළුව යාවත්කාලීන කරන්න',
    // Research Panel translations
    researchHub: 'පර්යේෂණ මධ්‍යස්ථානය',
    environmentalResearch: 'පාරිසරික පර්යේෂණ',
    searchResearch: 'පර්යේෂණ සොයන්න...',
    filterByType: 'වර්ගය අනුව පෙරහන් කරන්න',
    allTypes: 'සියලු වර්ග',
    scientificPaper: 'විද්‍යාත්මක පත්‍රිකාව',
    caseStudy: 'අධ්‍යයනය',
    report: 'වාර්තාව',
    news: 'පුවත්',
    addResearch: 'පර්යේෂණ එකතු කරන්න',
    type: 'වර්ගය',
    link: 'සබැඳිය',
    author: 'කතෘ',
    publishedDate: 'ප්‍රකාශිත දිනය',
    tags: 'ටැග්',
    connectToIssue: 'ගැටළුවට සම්බන්ධ කරන්න',
    noResearchFound: 'පර්යේෂණ හමු නොවීය',
    addNewResearch: 'නව පර්යේෂණ එකතු කරන්න',
    // Database Viewer translations
    databaseViewer: 'දත්ත සංචිත දර්ශකය',
    collectionStats: 'එකතු කිරීමේ සංඛ්‍යාලේඛන',
    issuesCount: 'ගැටළු',
    researchCount: 'පර්යේෂණ',
    usersCount: 'පරිශීලකයින්',
    refresh: 'නැවුම් කරන්න',
    exportData: 'දත්ත නිකුත් කරන්න',
    collection: 'එකතුව',
    documents: 'ලේඛන',
    viewDocument: 'ලේඛනය බලන්න',
    close: 'වසන්න',
    rawData: 'අමු දත්ත',
    // Toast notifications
    toastSuccess: 'සාර්ථකයි',
    toastError: 'දෝෂය',
    toastInfo: 'තොරතුරු',
    toastWarning: 'අනතුරු ඇඟවීම',
  },
  ta: {
    appName: 'சூழல் பாதுகாவலர்',
    map: 'வரைபடம்',
    report: 'புகாரளி',
    issues: 'பிரச்சினைகள்',
    research: 'ஆராய்ச்சி',
    database: 'தரவுத்தளம்',
    settings: 'அமைப்புகள்',
    theme: '🌓 கருப்பொருள்',
    light: 'ஒளி',
    dark: 'இருண்ட',
    language: '🌐 மொழி',
    success: '✅ பிரச்சினை வெற்றிகரமாகப் புகாரளிக்கப்பட்டது!',
    error: '❌ பிரச்சினையைப் புகாரளிப்பது தோல்வியுற்றது',
    deleteConfirm: 'இந்த பிரச்சினையை நீக்குவது உறுதியா?',
    deleteSuccess: '✅ பிரச்சினை வெற்றிகரமாக நீக்கப்பட்டது',
    deleteError: '❌ பிரச்சினையை நீக்குவது தோல்வியுற்றது',
    resolveSuccess: '✅ பிரச்சினை தீர்க்கப்பட்டதாக குறிக்கப்பட்டது!',
    resolveError: '❌ பிரச்சினையைத் தீர்க்க முடியவில்லை',
    editSuccess: '✅ பிரச்சினை வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
    editError: '❌ பிரச்சினையை புதுப்பிக்க முடியவில்லை',
    loading: 'ஏற்றுகிறது...',
    backendError: '⚠️ பேக்எண்ட் சர்வருடன் இணைக்க முடியவில்லை. சர்வர் போர்ட் 5001 இல் இயங்குகிறதா என்பதை உறுதிப்படுத்தவும்',
    noLocation: 'தயவுசெய்து முதலில் வரைபடத்தில் ஒரு இருப்பிடத்தைத் தேர்ந்தெடுக்கவும்',
    fillFields: 'தயவுசெய்து தேவையான அனைத்து புலங்களையும் நிரப்பவும்',
    districtSelected: '📍 {{district}} மாவட்டம் தேர்ந்தெடுக்கப்பட்டது',
    // Report Form translations
    reportTitle: 'சுற்றுச்சூழல் பிரச்சினையைப் புகாரளிக்கவும்',
    title: 'தலைப்பு',
    titlePlaceholder: 'பிரச்சினை தலைப்பை உள்ளிடுக',
    description: 'விளக்கம்',
    descriptionPlaceholder: 'சுற்றுச்சூழல் பிரச்சினையை விவரிக்கவும்...',
    district: 'மாவட்டம்',
    selectDistrict: 'மாவட்டத்தைத் தேர்ந்தெடுக்கவும்',
    location: 'இருப்பிடம்',
    selectedLocation: 'தேர்ந்தெடுக்கப்பட்ட இருப்பிடம்',
    latitude: 'அட்சரேகை',
    longitude: 'தீர்க்கரேகை',
    images: 'படங்கள்',
    uploadImages: 'படங்களைப் பதிவேற்றுக',
    dragImages: 'பதிவேற்ற கிளிக் செய்யவும் அல்லது படங்களை இழுக்கவும்',
    mapImages: 'வரைபடம்/செயற்கைக்கோள் படங்கள்',
    uploadMapImages: 'வரைபடம் அல்லது செயற்கைக்கோள் படங்களைப் பதிவேற்றுக',
    dragMapImages: 'பதிவேற்ற வரைபடம்/செயற்கைக்கோள் படங்களை கிளிக் செய்யவும் அல்லது இழுக்கவும்',
    pdfs: 'PDF ஆவணங்கள்',
    uploadPDFs: 'PDF ஆவணங்களைப் பதிவேற்றுக',
    dragPDFs: 'பதிவேற்ற PDF ஆவணங்களை கிளிக் செய்யவும் அல்லது இழுக்கவும்',
    submitReport: 'புகாரைச் சமர்ப்பி',
    cancel: 'ரத்து செய்',
    backToMap: 'வரைபடத்திற்குத் திரும்பு',
    // Issues List translations
    environmentalIssues: 'சுற்றுச்சூழல் பிரச்சினைகள்',
    searchIssues: 'பிரச்சினைகளைத் தேடுக...',
    filterByStatus: 'நிலை மூலம் வடிகட்டுக',
    all: 'அனைத்தும்',
    open: 'திறந்த',
    resolved: 'தீர்க்கப்பட்டது',
    inProgress: 'முன்னேற்றத்தில்',
    noIssuesFound: 'பிரச்சினைகள் எதுவும் கிடைக்கவில்லை',
    noIssuesReported: 'இதுவரை எந்த சுற்றுச்சூழல் பிரச்சினையும் புகாரளிக்கப்படவில்லை',
    beFirst: 'பிரச்சினையைப் புகாரளிப்பதில் முதலில் இருங்கள்',
    reportNewIssue: 'புதிய பிரச்சினையைப் புகாரளிக்கவும்',
    delete: 'நீக்கு',
    edit: 'திருத்து',
    resolve: 'தீர்க்க',
    connectResearch: 'ஆராய்ச்சியை இணைக்கவும்',
    viewDetails: 'விவரங்களைக் காண்க',
    status: 'நிலை',
    reportedOn: 'புகாரளிக்கப்பட்ட தேதி',
    reportedBy: 'புகாரளித்தவர்',
    actions: 'செயல்கள்',
    resolutionNotes: 'தீர்வு குறிப்புகள்',
    enterResolutionNotes: 'தீர்வு குறிப்புகளை உள்ளிடுக...',
    resolveIssue: 'பிரச்சினையைத் தீர்க்க',
    confirmResolve: 'தீர்ப்பதை உறுதிப்படுத்துக',
    editIssue: 'பிரச்சினையைத் திருத்துக',
    updateIssue: 'பிரச்சினையைப் புதுப்பிக்கவும்',
    // Research Panel translations
    researchHub: 'ஆராய்ச்சி மையம்',
    environmentalResearch: 'சுற்றுச்சூழல் ஆராய்ச்சி',
    searchResearch: 'ஆராய்ச்சியைத் தேடுக...',
    filterByType: 'வகை மூலம் வடிகட்டுக',
    allTypes: 'அனைத்து வகைகளும்',
    scientificPaper: 'அறிவியல் ஆவணம்',
    caseStudy: 'வழக்கு ஆய்வு',
    report: 'அறிக்கை',
    news: 'செய்தி',
    addResearch: 'ஆராய்ச்சியைச் சேர்க்க',
    type: 'வகை',
    link: 'இணைப்பு',
    author: 'ஆசிரியர்',
    publishedDate: 'வெளியிடப்பட்ட தேதி',
    tags: 'குறிச்சொற்கள்',
    connectToIssue: 'பிரச்சினையுடன் இணைக்க',
    noResearchFound: 'ஆராய்ச்சி எதுவும் கிடைக்கவில்லை',
    addNewResearch: 'புதிய ஆராய்ச்சியைச் சேர்க்க',
    // Database Viewer translations
    databaseViewer: 'தரவுத்தள காட்சியாளர்',
    collectionStats: 'சேகரிப்பு புள்ளிவிவரங்கள்',
    issuesCount: 'பிரச்சினைகள்',
    researchCount: 'ஆராய்ச்சி',
    usersCount: 'பயனர்கள்',
    refresh: 'புதுப்பி',
    exportData: 'தரவை ஏற்றுமதி செய்',
    collection: 'சேகரிப்பு',
    documents: 'ஆவணங்கள்',
    viewDocument: 'ஆவணத்தைக் காண்க',
    close: 'மூடு',
    rawData: 'மூல தரவு',
    // Toast notifications
    toastSuccess: 'வெற்றி',
    toastError: 'பிழை',
    toastInfo: 'தகவல்',
    toastWarning: 'எச்சரிக்கை',
  },
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'en';
  });

  const t = (key, params = {}) => {
    let text = translations[language][key] || translations.en[key] || key;
    // Replace parameters like {{param}}
    Object.keys(params).forEach(param => {
      text = text.replace(new RegExp(`{{${param}}}`, 'g'), params[param]);
    });
    return text;
  };

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, t, changeLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};